terminate called after throwing an instance of 'std::out_of_range'
  what():  stoi
Aborted (core dumped)

Wniosek: std::stoi() orientuje się,że mój napis nie jest możliwy do skonwertowania do typu liczbowego o szerokości 32 bitów ze znakiem.
